front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:accueil }

layout:
    path:     /layout
    defaults: { _controller: FrontBundle:Default:layout }
accueil:
    path:     /accueil
    defaults: { _controller: FrontBundle:Default:accueil }
wishlist:
    path:     /wishlist
    defaults: { _controller: FrontBundle:Default:wishlist }
about:
    path:     /about
    defaults: { _controller: FrontBundle:Default:about }
care:
    path:     /care
    defaults: { _controller: FrontBundle:Default:care }
codes:
    path:     /codes
    defaults: { _controller: FrontBundle:Default:codes }
contact:
    path:     /contact
    defaults: { _controller: FrontBundle:Default:contact }
faqs:
    path:     /faqs
    defaults: { _controller: FrontBundle:Default:faqs }
hold:
    path:     /hold
    defaults: { _controller: FrontBundle:Default:hold }
kitchen:
    path:     /kitchen
    defaults: { _controller: FrontBundle:Default:kitchen }
login:
    path:     /login
    defaults: { _controller: FrontBundle:Default:login }
offer:
    path:     /offer
    defaults: { _controller: FrontBundle:Default:offer }
register:
    path:     /register
    defaults: { _controller: FrontBundle:Default:register }
shipping:
    path:     /shipping
    defaults: { _controller: FrontBundle:Default:shipping }
single:
    path:     /single/{id}
    defaults: { _controller: UserBundle:Produits:single }
single2:
    path:     /single2/{id}
    defaults: { _controller: UserBundle:Produits:single2 }
single3:
    path:     /single3/{id}
    defaults: { _controller: UserBundle:Produits:single3 }
terms:
    path:     /terms
    defaults: { _controller: FrontBundle:Default:terms }

ROLE_USER:
    path:     /fos/user/test
    defaults: { _controller: FrontBundle:Default:testRoleUser }
ROLE_ADMIN:
    path:     /fos/admin/test
    defaults: { _controller: FrontBundle:Default:testRoleAdmin }
Boutique:
    path:     /Boutique
    defaults: { _controller: UserBundle:Produits:affichageProduits }
nosJouets:
    path:     /nosJouets
    defaults: { _controller: UserBundle:Produits:nosJouets }
nosVetements:
    path:     /nosVetements
    defaults: { _controller: UserBundle:Produits:nosVetements }
nosFournitures:
    path:     /nosFournitures
    defaults: { _controller: UserBundle:Produits:nosFournitures }

