front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:accueil1 }

layout:
    path:     /layout
    defaults: { _controller: FrontBundle:Default:layout }
accueil1:
    path:     /accueil1
    defaults: { _controller: FrontBundle:Default:accueil1 }
wishlist:
    path:     /wishlist
    defaults: { _controller: FrontBundle:Default:wishlist }
about:
    path:     /about
    defaults: { _controller: FrontBundle:Default:about }
plus:
    path:     /plus/{id}
    defaults: { _controller: UserBundle:Garderies:plus }
enseignants:
    path:     /enseignants/{id}
    defaults: { _controller: UserBundle:Enseignants:enseignants }
activiteFront:
    path:     /activiteFront/{id}
    defaults: { _controller: UserBundle:Activite:affichageF }
etapeF:
    path:     /etapeF/{id}
    defaults: { _controller: UserBundle:Etape:affichageF }
participer:
    path:     /participer/{idE}/{id}
    defaults: { _controller: UserBundle:Etape:participer }
annuler:
    path:     /annuler/{idE}/{id}
    defaults: { _controller: UserBundle:Etape:annuler }
care:
    path:     /care
    defaults: { _controller: UserBundle:Garderies:affichage }
codes:
    path:     /codes
    defaults: { _controller: FrontBundle:Default:codes }
contact:
    path:     /contact
    defaults: { _controller: FrontBundle:Default:contact }
faqs:
    path:     /faqs
    defaults: { _controller: FrontBundle:Default:faqs }
hold:
    path:     /hold
    defaults: { _controller: FrontBundle:Default:hold }
kitchen:
    path:     /kitchen
    defaults: { _controller: FrontBundle:Default:kitchen }
login:
    path:     /login
    defaults: { _controller: FrontBundle:Default:login }
offer:
    path:     /offer
    defaults: { _controller: FrontBundle:Default:offer }
register:
    path:     /register
    defaults: { _controller: FrontBundle:Default:register }
shipping:
    path:     /shipping
    defaults: { _controller: FrontBundle:Default:shipping }
single:
    path:     /single
    defaults: { _controller: FrontBundle:Default:single }
terms:
    path:     /terms
    defaults: { _controller: FrontBundle:Default:terms }
profil:
    path:     /profil
    defaults: { _controller: UserBundle:OffresBabysitter:ajoutOffres }
inscriEnfant:
    path:     /inscriEnfant/{id}
    defaults: { _controller: UserBundle:Enfants:inscrire }
profilBB:
    path:     /profilBB
    defaults: { _controller: UserBundle:OffresBabysitter:affichage }
delete:
    path:     /supprimer/{ref1}
    defaults: { _controller: UserBundle:OffresBabysitter:delete }
modifier:
    path:     /modifier/{ref2}
    defaults: { _controller: UserBundle:OffresBabysitter:modifier }
profilParent:
    path:     /profilParent
    defaults: { _controller: UserBundle:OffresBabysitter:profilParent }
ROLE_USER:
    path:     /fos/user/test
    defaults: { _controller: FrontBundle:Default:testRoleUser }
ROLE_ADMIN:
    path:     /fos/admin/test
    defaults: { _controller: FrontBundle:Default:testRoleAdmin }
ListeCov:
    path:     /ListeCov
    defaults: { _controller: UserBundle:Covoiturage:afficher }
AjouterCov:
    path:     /AjouterCov
    defaults: { _controller: UserBundle:Covoiturage:ajouter }