front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:accueil }

layout:
    path:     /layout
    defaults: { _controller: FrontBundle:Default:layout }
accueil:
    path:     /accueil
    defaults: { _controller: FrontBundle:Default:accueil }
wishlist:
    path:     /wishlist
    defaults: { _controller: FrontBundle:Default:wishlist }
about:
    path:     /about
    defaults: { _controller: FrontBundle:Default:about }
plus:
    path:     /plus
    defaults: { _controller: FrontBundle:Default:plus }
care:
    path:     /care
    defaults: { _controller: UserBundle:Garderies:affichage }
codes:
    path:     /codes
    defaults: { _controller: FrontBundle:Default:codes }
contact:
    path:     /contact
    defaults: { _controller: FrontBundle:Default:contact }
faqs:
    path:     /faqs
    defaults: { _controller: FrontBundle:Default:faqs }
hold:
    path:     /hold
    defaults: { _controller: FrontBundle:Default:hold }
kitchen:
    path:     /kitchen
    defaults: { _controller: FrontBundle:Default:kitchen }
login:
    path:     /login
    defaults: { _controller: FrontBundle:Default:login }
offer:
    path:     /offer
    defaults: { _controller: FrontBundle:Default:offer }
register:
    path:     /register
    defaults: { _controller: FrontBundle:Default:register }
shipping:
    path:     /shipping
    defaults: { _controller: FrontBundle:Default:shipping }
single:
    path:     /single
    defaults: { _controller: FrontBundle:Default:single }
terms:
    path:     /terms
    defaults: { _controller: FrontBundle:Default:terms }
profil:
    path:     /profil
    defaults: { _controller: FrontBundle:OffresBabysitter:gestionOffres }

ROLE_USER:
    path:     /fos/user/test
    defaults: { _controller: FrontBundle:Default:testRoleUser }
ROLE_ADMIN:
    path:     /fos/admin/test
    defaults: { _controller: FrontBundle:Default:testRoleAdmin }

