message:
    resource: "@MessageBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type:      annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /fos
back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /back
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /chat
message:
    resource: "@MessageBundle/Resources/config/routing.yml"
    prefix:   /chat
