user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
ROLE_USER:
    path:     /fos/user/test
    defaults: { _controller: UserBundle:Default:testRoleUser }
ROLE_ADMIN:
    path:     /fos/admin/test
    defaults: { _controller: UserBundle:Default:testRoleAdmin }

gestion_produits:
    path:     /gestionProduits
    defaults: { _controller: UserBundle:Produits:gestionProduits }


ajouter:
    path:     /ajouter
    defaults: { _controller: UserBundle:Covoiturage:ajouter }

afficher:
    path:     /afficher
    defaults: { _controller: UserBundle:Covoiturage:afficher }

modifier:
    path:     /modifier
    defaults: { _controller: UserBundle:Covoiturage:modifier }
