user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
ROLE_USER:
    path:     /fos/user/test
    defaults: { _controller: UserBundle:Default:testRoleUser }
ROLE_ADMIN:
    path:     /fos/admin/test
    defaults: { _controller: UserBundle:Default:testRoleAdmin }

gestion_produits:
    path:     /gestionProduits
    defaults: { _controller: UserBundle:Produits:gestionProduits }
gestion_profil:
    path:     /profil
    defaults: { _controller: UserBundle:OffresBabysitter:ajoutOffres }
profil_BB:
    path:     /profilBB
    defaults: { _controller: UserBundle:OffresBabysitter:affichage}


