user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
ROLE_USER:
    path:     /fos/user/test
    defaults: { _controller: UserBundle:Default:testRoleUser }
ROLE_ADMIN:
    path:     /fos/admin/test
    defaults: { _controller: UserBundle:Default:testRoleAdmin }

gestion_produits:
    path:     /gestionProduits
    defaults: { _controller: UserBundle:Produits:gestionProduits }
<<<<<<< HEAD

gestion_promotions:
    path:     /gestionPromotions
    defaults: { _controller: UserBundle:Promotions:gestionPromotions }

supprimer_promotion:
    path:     /supprimerPromotion
    defaults: { _controller: UserBundle:Promotions:supprimerPromotion }

modifier_promotion:
    path:     /modifierPromotion
    defaults: { _controller: UserBundle:Promotions:modifierPromotion }
=======
gestion_profil:
    path:     /profil
    defaults: { _controller: UserBundle:OffresBabysitter:ajoutOffres }
profil_BB:
    path:     /profilBB
    defaults: { _controller: UserBundle:OffresBabysitter:affichage}
<<<<<<< HEAD
=======




>>>>>>> 2fa14e4bda6c5236979f4abcde7dca5391e436ed
ajouter:
    path:     /ajouter
    defaults: { _controller: UserBundle:Covoiturage:ajouter }

afficher:
    path:     /afficher
    defaults: { _controller: UserBundle:Covoiturage:afficher }

modifier:
    path:     /modifier
    defaults: { _controller: UserBundle:Covoiturage:modifier }
>>>>>>> 8fbaa7926e73845be87484c9bec92a7e181cb554
