user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
ROLE_USER:
    path:     /fos/user/test
    defaults: { _controller: UserBundle:Default:testRoleUser }
ROLE_ADMIN:
    path:     /fos/admin/test
    defaults: { _controller: UserBundle:Default:testRoleAdmin }
<<<<<<< HEAD
=======
gestion_produits:
    path:     /gestionProduits
    defaults: { _controller: UserBundle:Produits:gestionProduits }
>>>>>>> 16fd5270e2649175bcb087f14c52d6db5e4f90e6
