user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
ROLE_USER:
    path:     /fos/user/test
    defaults: { _controller: UserBundle:Default:testRoleUser }
ROLE_ADMIN:
    path:     /fos/admin/test
    defaults: { _controller: UserBundle:Default:testRoleAdmin }
gestion_produits:
    path:     /gestionProduits
    defaults: { _controller: UserBundle:Produits:gestionProduits }

gestion_promotions:
    path:     /gestionPromotions
    defaults: { _controller: UserBundle:Promotions:gestionPromotions }

supprimer_promotion:
    path:     /supprimerPromotion
    defaults: { _controller: UserBundle:Promotions:supprimerPromotion }

modifier_promotion:
    path:     /modifierPromotion
    defaults: { _controller: UserBundle:Promotions:modifierPromotion }
