<?php

namespace UserBundle\Repository;

/**
 * EtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeRepository extends \Doctrine\ORM\EntityRepository
{
    function findNb()
    {
        $query=$this->getEntityManager()->createQuery(
            "select count(m) from UserBundle:Etape m");
        return $query->getResult();

    }
}
