<?php

namespace UserBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffresBabysitterRepository extends EntityRepository
{
function findByidbb($p)
{
    $query=$this->getEntityManager()->createQuery(
        "select m from UserBundle:OffresBabysitter m where m.idbb=:x "
    )->setParameter('x','%'.$p.'%');
    return $query->getResult();

}
}

