<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    function findDateDebut()
    {
        $query=$this->getEntityManager()->createQuery(
            "select m  From UserBundle:Activite m where m.dateFin  > CURRENT_DATE()");

        return $query->getResult();
    }

}
